In [1]:
import torch.nn as nn
import torch

In [2]:
m = nn.BatchNorm1d(2,affine=False)
data = torch.tensor([[1,3],[3,2],[8,4]],dtype=torch.float32)
result = m(data)

In [3]:
result

tensor([[-1.0190,  0.0000],
        [-0.3397, -1.2247],
        [ 1.3587,  1.2247]])

### Calculating Statistics

In [4]:
mean = data.mean(dim=0)
var = data.var(dim=0,unbiased=False)
eps = 0.00001
momentum = 0.1

### Normalizing - Type One

In [5]:
y = (data-mean)/(torch.sqrt(var+eps))

In [6]:
y

tensor([[-1.0190,  0.0000],
        [-0.3397, -1.2247],
        [ 1.3587,  1.2247]])

### Normalizing - Way Two

In [7]:
var2 = torch.sum((data-mean) *(data-mean),dim=0)/3

In [8]:
y = (data-mean)/(torch.sqrt(var2+eps))

In [9]:
y

tensor([[-1.0190,  0.0000],
        [-0.3397, -1.2247],
        [ 1.3587,  1.2247]])