In [5]:
import torch
import torch.nn as nn
torch.manual_seed(2)

In [6]:
embedding = nn.Embedding(3, 2)
idx = torch.tensor([0,1,2])
data_em = embedding(idx)


### Precomputed Postional embedding

In [7]:
positional_embedding = torch.tensor([[0.3901, 0.9088],
        [0.5334, 0.7073],
        [0.7116, 0.2050]])

In [8]:
positional_embedding

tensor([[0.3901, 0.9088],
        [0.5334, 0.7073],
        [0.7116, 0.2050]])

### Adding postional embedding to the input

In [24]:
data_em += positional_embedding

In [25]:
positional_embedding

tensor([[0.3901, 0.9088],
        [0.5334, 0.7073],
        [0.7116, 0.2050]])

### Creating the Q,K,V

In [26]:
query_nn =  torch.tensor([[0.7197, 0.3081],
        [0.3892, 0.2259],
        [0.3430, 0.0367]])

key_nn = torch.tensor([[0.7133, 0.6944],
        [0.5993, 0.7455],
        [0.7119, 0.5221]])
value_nn = torch.tensor([[0.5530, 0.5382],
        [0.7668, 0.8359],
        [0.8591, 0.7898]])

### Multiplying Q and K to get the energies

In [27]:
energy = torch.einsum("hd,jd->hj", [query_nn, key_nn])

In [28]:
energy

tensor([[0.7273, 0.6610, 0.6732],
        [0.4345, 0.4017, 0.3950],
        [0.2701, 0.2329, 0.2633]])

### Creating the mask

In [29]:
mask =torch.tensor([[0, -9721983478912, -9721983478912],
        [0, 0, -9721983478912],
        [0, 0, 0]])

In [30]:
mask_scaled_Added = (energy/1.41421356237)+mask

In [31]:
mask_scaled_Added

tensor([[ 5.1428e-01, -9.7220e+12, -9.7220e+12],
        [ 3.0722e-01,  2.8401e-01, -9.7220e+12],
        [ 1.9102e-01,  1.6470e-01,  1.8621e-01]])

### Computing attention

In [35]:
attention = torch.softmax(mask_scaled_Added,dim=1)

In [36]:
context_vector = torch.mm(attention,value_nn)

In [34]:
context_vector

tensor([[0.5530, 0.5382],
        [0.6587, 0.6853],
        [0.7257, 0.7202]])