$h_{t}=\tanh \left(W_{i h} x_{t}+b_{i h}+W_{h h} h_{(t-1)}+b_{h h}\right)$

In [1]:
import torch.nn as nn
import torch
torch.manual_seed(2)

In [2]:
layer_num = 1
rnn = nn.RNN(input_size=2,hidden_size=3,num_layers=layer_num ,batch_first=True) #my RNN
input = torch.rand(1,2,2) #input of  shape (batch ,seq_len,  input_size):
hidden = torch.rand(layer_num*1, 1,3) # h of shape (num_layers * num_directions, batch,hidden_size)



In [3]:
output,next_hidden = rnn(input,hidden)

In [4]:
output

tensor([[[-0.2157,  0.5237, -0.5189],
         [-0.2261,  0.7824, -0.3614]]], grad_fn=<TransposeBackward1>)

In [5]:
next_hidden

tensor([[[-0.2261,  0.7824, -0.3614]]], grad_fn=<StackBackward0>)

In [41]:
input

tensor([[[0.4660, 0.4604],
         [0.8547, 0.4525]]])